### ISSUE TITLE
Issue when running

### ISSUE THREAD

**Issue by kumar-b5** [androlo/bank.js#2]
Hello, I tried to run this example with conveting this to eris:cli. I had created a test chain and deploy the contract using epm.yaml . Contract got deployed successfully. However, when I run on browser, it doesn't accept username for register for the first time. it directly displays the split screen with endow and trasfer option. and UserName : undefinded. I also get error when I press button "Endow"
Error: Error when Getting UserName. Am I missing anything here ?

**Comment by androlo** [comment]
This is an old repo, i am going to remove it. Sorry.
